# Generated by Django 5.2 on 2025-05-15 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('ویدیو', 'ویدیو'), ('عکس', 'عکس'), ('متن', 'متن')], max_length=50),
        ),
        migrations.CreateModel(
            name='PublishReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_success', models.BooleanField(default=False)),
                ('instagram_error', models.TextField(blank=True, null=True)),
                ('telegram_success', models.BooleanField(default=False)),
                ('telegram_error', models.TextField(blank=True, null=True)),
                ('facebook_success', models.BooleanField(default=False)),
                ('facebook_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.content')),
            ],
        ),
    ]
